/* Automatically generated by p4c-ebpf from ./test.p4i on Mon Jan  8 19:22:44 2018
 */
#ifndef _P4_GEN_HEADER_
#define _P4_GEN_HEADER_
#include <uapi/linux/bpf.h>
#include <uapi/linux/if_ether.h>
#include <uapi/linux/if_packet.h>
#include <uapi/linux/ip.h>
#include <linux/skbuff.h>
#include <linux/netdevice.h>
#define MAP_PATH "/sys/fs/bpf"
struct Headers_t {
};

#if CONTROL_PLANE
void initialize_tables() 
{
    u32 ebpf_zero = 0;
}
#endif
#endif
